Start-Process powershell -ArgumentList "-NoExit", "mvn -q -pl config-service spring-boot:run -Dspring-boot.run.profiles=local"
Start-Process powershell -ArgumentList "-NoExit", "mvn -q -pl discovery-service spring-boot:run -Dspring-boot.run.profiles=local"
Start-Process powershell -ArgumentList "-NoExit", "mvn -q -pl gateway spring-boot:run -Dspring-boot.run.profiles=local"
Start-Process powershell -ArgumentList "-NoExit", "mvn -q -pl user-service spring-boot:run -Dspring-boot.run.profiles=local"
Start-Process powershell -ArgumentList "-NoExit", "mvn -q -pl question-service spring-boot:run -Dspring-boot.run.profiles=local"
Start-Process powershell -ArgumentList "-NoExit", "mvn -q -pl exam-service spring-boot:run -Dspring-boot.run.profiles=local"
Start-Process powershell -ArgumentList "-NoExit", "mvn -q -pl career-service spring-boot:run -Dspring-boot.run.profiles=local"
Start-Process powershell -ArgumentList "-NoExit", "mvn -q -pl news-service spring-boot:run -Dspring-boot.run.profiles=local"
Start-Process powershell -ArgumentList "-NoExit", "uvicorn nlp-service.app:app --host 0.0.0.0 --port 7000 --reload"
